language: python
sudo: true

script:
  - tar zcvf app-agent-linux-amd64.tar.gz app-agent-linux-amd64
before_install:
  - openssl aes-256-cbc -K $encrypted_72b2f7b1b831_key -iv $encrypted_72b2f7b1b831_iv -in key.yaml.enc -out key.yaml -d
install:
  - sudo pip install -U urllib3
  - sudo pip install -U requests
  - sudo pip install -U futures
  - sudo pip install -U qsctl

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "ByY8NEdSfI3GmoDnr+HiaRDROzDaKiW8dnOOQvKbiiQE8Hy/L6rbBqVXo+ENthZhsdAaKFwu/A3xoNZCRRibnVl4rYyuOhTwqub3zuWUkE8QH/+a7cWdXkgB2/gMLtdo7b/hbh7G3koERRfTnbsJD/7gOmCbFpIIBFcY3Z7R/bghMXTgweuUGlFmXF5mIMwVIJDwES5Z54V/Uwn9LcZsNeaoYJGL1/a8ycOXU8KOHqrVFBTYzOkt3MHdy2is4pT7UDeQu/9WrYVQDsV8Ao4cMMrSmtOCwdFRU9HUbYq6/+e+Lh+h9hZlnstiUMYPIxbnei7dP1xNwZ/Sw+s5P+y2jc0jkPf+tUdsaofinhR4qvS2vcuT52zTMJQSr2ErWv215YC6ejrLz2KbKYw1Ovn123wAXes9mB5u5U0SctUXDMpiObPw4zsjIxp/JPHbQ4xpPIZj5qYaqu7y8vPoMC1X+6JfZcLAHcmaApI6Rol5FZTkwP2t2soXTFUB9cMIEFdzI63Hk9F67z1KY5BlCssukf+LM+m4g3d2ROrO83LBT5ckGT+sC8X+6Y6X/RNsPuJ/FBg3H3aR7ATpzoTH8prsB89BARsx3o0eg3jYX+9zodws5Wddpr/EP5nPuQOQNyyrNR8xtcO1B7HrKVzAllsLnksX8t7SSPgwyMrkXkIRiSg="
    file:
      - "app-agent-linux-amd64.tar.gz"
    on:
      tags: true
      
after_deploy:
  - qsctl cp -f app-agent-linux-amd64.tar.gz qs://appcenter-docs/developer-guide/scripts/app-agent-linux-amd64.tar.gz -c key.yaml -z pek3a
